{"uuid": "afba1b59-4feb-40cf-b982-0eb7c7136923", "children": ["1394d980-046a-4f67-a900-0d6df0421241"], "befores": [{"name": "create_driver", "status": "broken", "statusDetails": {"message": "requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n", "trace": "  File \"/Users/mohsenakbari/Downloads/Python-Selenium-Pytest-main/.venv/lib/python3.10/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/mohsenakbari/Downloads/Python-Selenium-Pytest-main/.venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/mohsenakbari/Downloads/Python-Selenium-Pytest-main/.venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/mohsenakbari/Downloads/Python-Selenium-Pytest-main/tests/conftest.py\", line 61, in create_driver\n    driver = webdriver.Chrome(ChromeDriverManager().install(), options=opts)\n  File \"/Users/mohsenakbari/Downloads/Python-Selenium-Pytest-main/.venv/lib/python3.10/site-packages/webdriver_manager/chrome.py\", line 32, in install\n    driver_path = self._get_driver_path(self.driver)\n  File \"/Users/mohsenakbari/Downloads/Python-Selenium-Pytest-main/.venv/lib/python3.10/site-packages/webdriver_manager/manager.py\", line 22, in _get_driver_path\n    driver_version = driver.get_version()\n  File \"/Users/mohsenakbari/Downloads/Python-Selenium-Pytest-main/.venv/lib/python3.10/site-packages/webdriver_manager/driver.py\", line 40, in get_version\n    return self.get_latest_release_version()\n  File \"/Users/mohsenakbari/Downloads/Python-Selenium-Pytest-main/.venv/lib/python3.10/site-packages/webdriver_manager/driver.py\", line 64, in get_latest_release_version\n    validate_response(resp)\n  File \"/Users/mohsenakbari/Downloads/Python-Selenium-Pytest-main/.venv/lib/python3.10/site-packages/webdriver_manager/utils.py\", line 81, in validate_response\n    raise ValueError(resp.json())\n  File \"/Users/mohsenakbari/Downloads/Python-Selenium-Pytest-main/.venv/lib/python3.10/site-packages/requests/models.py\", line 978, in json\n    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)\n"}, "start": 1737705730833, "stop": 1737705731192}], "start": 1737705730833, "stop": 1737705731266}