{"uuid": "447e4c38-f37b-49d1-ac05-16ccf196fbf2", "children": ["a9365a9f-c9ef-46b8-b22c-eaed08f2c68c"], "befores": [{"name": "create_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line\n\n", "trace": "  File \"/Users/mohsenakbari/Downloads/Python-Selenium-Pytest-main/.venv/lib/python3.10/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/mohsenakbari/Downloads/Python-Selenium-Pytest-main/.venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/mohsenakbari/Downloads/Python-Selenium-Pytest-main/.venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/mohsenakbari/Downloads/Python-Selenium-Pytest-main/tests/conftest.py\", line 47, in create_driver\n    driver = webdriver.Firefox(executable_path=GeckoDriverManager().install())\n  File \"/Users/mohsenakbari/Downloads/Python-Selenium-Pytest-main/.venv/lib/python3.10/site-packages/selenium/webdriver/firefox/webdriver.py\", line 170, in __init__\n    RemoteWebDriver.__init__(\n  File \"/Users/mohsenakbari/Downloads/Python-Selenium-Pytest-main/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/Users/mohsenakbari/Downloads/Python-Selenium-Pytest-main/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 252, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"/Users/mohsenakbari/Downloads/Python-Selenium-Pytest-main/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/mohsenakbari/Downloads/Python-Selenium-Pytest-main/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1737707213693, "stop": 1737707220838}], "start": 1737707213693, "stop": 1737707220895}